/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bioskop;

/**
 *
 * @author Acer
 */

import Data.Manage_Kursi;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import javax.swing.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class pilihan extends javax.swing.JFrame {

    koneksiDB x;      //deklarasi kelas
    /**
     * Creates new form booking
     */
    String ket="";
    String jdl="";
    String Std="";
    
    public pilihan() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nomorkursi = new javax.swing.JTextField();
        btn_booked = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        namaStudio = new javax.swing.JLabel();
        namaFilm = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fix_tgl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fix_jam = new javax.swing.JLabel();
        fix_bln = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fix_thn = new javax.swing.JLabel();
        fix_mnt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fix_harga = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("BOOKING KURSI");

        jLabel4.setText("KURSI NOMOR");

        jLabel3.setText("STUDIO");

        jLabel2.setText("NAMA FILM");

        btn_booked.setText("BOOKING");
        btn_booked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookedActionPerformed(evt);
            }
        });

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        namaStudio.setText("...");

        namaFilm.setText("...");

        jLabel5.setText("JADWAL ");

        fix_tgl.setText("..");

        jLabel6.setText("-");

        fix_jam.setText("..");

        fix_bln.setText("..");

        jLabel7.setText("-");

        jLabel9.setText(":");

        fix_thn.setText("..");

        fix_mnt.setText("..");

        jLabel8.setText("HARGA");

        fix_harga.setText("..");

        jLabel10.setText("Rp.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel1))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(namaStudio)
                                    .addComponent(txt_nomorkursi, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fix_tgl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fix_bln)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fix_thn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fix_jam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fix_mnt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fix_harga)))))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btn_booked, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fix_tgl)
                    .addComponent(jLabel6)
                    .addComponent(fix_jam)
                    .addComponent(fix_bln)
                    .addComponent(jLabel7)
                    .addComponent(fix_thn)
                    .addComponent(fix_mnt)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaFilm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaStudio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_nomorkursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fix_harga)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_booked)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setKursi(String blabla){
        this.ket=blabla;
        txt_nomorkursi.setText(this.ket);
    }
    public void setJudul(String kukuku){
        this.jdl = kukuku;
       
        System.out.println(this.jdl);
    }
    public void setStudio(String nono){
        this.Std = nono;
        namaStudio.setText(this.Std);
        System.out.println(this.Std);
    }
    
    public void printTicket() throws PrinterException{
        JTextPane textPane = new JTextPane();
        textPane.setText("********************************\n" +
                        "        	   CINEMA 69   \n" +
                        "=====================\n" +
                        " "+namaFilm.getText()+"		       \n" +
                        " date : "+fix_tgl.getText()+"-"+fix_bln.getText()+"-"+fix_thn.getText()+"              \n" +
                        " time : "+fix_jam.getText()+":"+fix_mnt.getText()+":00		       \n" +
                        " studio: "+namaStudio.getText()+" / SEAT: "+txt_nomorkursi.getText()+" \n" +
                        " price : Rp. "+fix_harga.getText()+"	       \n" +
                        "********************************");
        textPane.print();
    }
    
    public void getIDT(){
        String studio = namaStudio.getText();
        koneksiDB db = new koneksiDB();
        ResultSet rs=null;
        try {
            rs=db.getData("select id_theater from theater where no_theater='"+studio+"';");
            while(rs.next()){
                this.Std = rs.getString("id_theater");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new theater().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btn_bookedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookedActionPerformed
        // TODO add your handling code here:
        String kursi = txt_nomorkursi.getText();
        String stt = "Booked";
        getIDT();
        String idTheater = this.Std;
        try {
            new Manage_Kursi().insert(kursi,stt,idTheater);
            JOptionPane.showMessageDialog(null, "Berhasil di booking.");
        } catch (SQLException ex) {
            Logger.getLogger(pilihan.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            printTicket();
        } catch (PrinterException ex) {
            Logger.getLogger(pilihan.class.getName()).log(Level.SEVERE, null, ex);
        }
        new FrameTransaksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_bookedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new theater().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_booked;
    public static javax.swing.JLabel fix_bln;
    public static javax.swing.JLabel fix_harga;
    public static javax.swing.JLabel fix_jam;
    public static javax.swing.JLabel fix_mnt;
    public static javax.swing.JLabel fix_tgl;
    public static javax.swing.JLabel fix_thn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel namaFilm;
    public static javax.swing.JLabel namaStudio;
    private javax.swing.JTextField txt_nomorkursi;
    // End of variables declaration//GEN-END:variables

    private void koneksiDB() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
